//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.AdminUI.MenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IMenuService")]
    public interface IMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenus", ReplyAction="http://tempuri.org/IMenuService/GetMenusResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.Menu> GetMenus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenu", ReplyAction="http://tempuri.org/IMenuService/GetMenuResponse")]
        Enterprise.Logic.Entities.Menu GetMenu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetCompleteMenu", ReplyAction="http://tempuri.org/IMenuService/GetCompleteMenuResponse")]
        Enterprise.Logic.Entities.Menu GetCompleteMenu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenu", ReplyAction="http://tempuri.org/IMenuService/AddMenuResponse")]
        Enterprise.Logic.Entities.Menu AddMenu(Enterprise.Logic.Entities.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenu", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuResponse")]
        bool UpdateMenu(Enterprise.Logic.Entities.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/DeleteMenu", ReplyAction="http://tempuri.org/IMenuService/DeleteMenuResponse")]
        bool DeleteMenu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenusByRestaurant", ReplyAction="http://tempuri.org/IMenuService/GetMenusByRestaurantResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.Menu> GetMenusByRestaurant(int restaurantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItemByRestaurant", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemByRestaurantResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemByRestaurant(int restaurantId, int menuId, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetByRestaurantTotalCount", ReplyAction="http://tempuri.org/IMenuService/GetByRestaurantTotalCountResponse")]
        int GetByRestaurantTotalCount(int restaurantId, int menuId, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItemByMenu", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemByMenuResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemByMenu(int menuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItemsByPage", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemsByPageResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemsByPage(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetTotalMenuItemCount", ReplyAction="http://tempuri.org/IMenuService/GetTotalMenuItemCountResponse")]
        int GetTotalMenuItemCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetBestSeller", ReplyAction="http://tempuri.org/IMenuService/GetBestSellerResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetBestSeller();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItem", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemResponse")]
        Enterprise.Logic.Entities.MenuItem GetMenuItem(int menuItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetRelatedMenuItem", ReplyAction="http://tempuri.org/IMenuService/GetRelatedMenuItemResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetRelatedMenuItem(int menuItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItems", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemsResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItemModels", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemModelsResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItemModel> GetMenuItemModels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenuItem", ReplyAction="http://tempuri.org/IMenuService/AddMenuItemResponse")]
        Enterprise.Logic.Entities.MenuItem AddMenuItem(Enterprise.Logic.Entities.MenuItem menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenuItem", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuItemResponse")]
        Enterprise.Logic.Entities.MenuItem UpdateMenuItem(Enterprise.Logic.Entities.MenuItem menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/DeleteMenuItem", ReplyAction="http://tempuri.org/IMenuService/DeleteMenuItemResponse")]
        bool DeleteMenuItem(int menuItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/IsMenuHaveMenuItem", ReplyAction="http://tempuri.org/IMenuService/IsMenuHaveMenuItemResponse")]
        bool IsMenuHaveMenuItem(int menuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuItemModelByMenu", ReplyAction="http://tempuri.org/IMenuService/GetMenuItemModelByMenuResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItemModel> GetMenuItemModelByMenu(int menuId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuServiceChannel : Enterprise.AdminUI.MenuService.IMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuServiceClient : System.ServiceModel.ClientBase<Enterprise.AdminUI.MenuService.IMenuService>, Enterprise.AdminUI.MenuService.IMenuService {
        
        public MenuServiceClient() {
        }
        
        public MenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.Menu> GetMenus() {
            return base.Channel.GetMenus();
        }
        
        public Enterprise.Logic.Entities.Menu GetMenu(int id) {
            return base.Channel.GetMenu(id);
        }
        
        public Enterprise.Logic.Entities.Menu GetCompleteMenu(int id) {
            return base.Channel.GetCompleteMenu(id);
        }
        
        public Enterprise.Logic.Entities.Menu AddMenu(Enterprise.Logic.Entities.Menu menu) {
            return base.Channel.AddMenu(menu);
        }
        
        public bool UpdateMenu(Enterprise.Logic.Entities.Menu menu) {
            return base.Channel.UpdateMenu(menu);
        }
        
        public bool DeleteMenu(int id) {
            return base.Channel.DeleteMenu(id);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.Menu> GetMenusByRestaurant(int restaurantId) {
            return base.Channel.GetMenusByRestaurant(restaurantId);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemByRestaurant(int restaurantId, int menuId, int page) {
            return base.Channel.GetMenuItemByRestaurant(restaurantId, menuId, page);
        }
        
        public int GetByRestaurantTotalCount(int restaurantId, int menuId, int page) {
            return base.Channel.GetByRestaurantTotalCount(restaurantId, menuId, page);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemByMenu(int menuID) {
            return base.Channel.GetMenuItemByMenu(menuID);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItemsByPage(int page) {
            return base.Channel.GetMenuItemsByPage(page);
        }
        
        public int GetTotalMenuItemCount() {
            return base.Channel.GetTotalMenuItemCount();
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetBestSeller() {
            return base.Channel.GetBestSeller();
        }
        
        public Enterprise.Logic.Entities.MenuItem GetMenuItem(int menuItemId) {
            return base.Channel.GetMenuItem(menuItemId);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetRelatedMenuItem(int menuItemId) {
            return base.Channel.GetRelatedMenuItem(menuItemId);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItem> GetMenuItems() {
            return base.Channel.GetMenuItems();
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItemModel> GetMenuItemModels() {
            return base.Channel.GetMenuItemModels();
        }
        
        public Enterprise.Logic.Entities.MenuItem AddMenuItem(Enterprise.Logic.Entities.MenuItem menu) {
            return base.Channel.AddMenuItem(menu);
        }
        
        public Enterprise.Logic.Entities.MenuItem UpdateMenuItem(Enterprise.Logic.Entities.MenuItem menu) {
            return base.Channel.UpdateMenuItem(menu);
        }
        
        public bool DeleteMenuItem(int menuItemId) {
            return base.Channel.DeleteMenuItem(menuItemId);
        }
        
        public bool IsMenuHaveMenuItem(int menuId) {
            return base.Channel.IsMenuHaveMenuItem(menuId);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.MenuItemModel> GetMenuItemModelByMenu(int menuId) {
            return base.Channel.GetMenuItemModelByMenu(menuId);
        }
    }
}
