//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.AdminUI.RestaurantService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantService.IRestaurantService")]
    public interface IRestaurantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantResponse")]
        Enterprise.Logic.Entities.Restaurant GetRestaurant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurants", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantsResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.Restaurant> GetRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/AddRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/AddRestaurantResponse")]
        Enterprise.Logic.Entities.Restaurant AddRestaurant(Enterprise.Logic.Entities.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantResponse")]
        bool UpdateRestaurant(Enterprise.Logic.Entities.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantResponse")]
        bool DeleteRestaurant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurantCategory", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantCategoryResponse")]
        Enterprise.Logic.Entities.RestaurantCategory GetRestaurantCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurantCategories", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantCategoriesResponse")]
        System.Collections.Generic.List<Enterprise.Logic.Entities.RestaurantCategory> GetRestaurantCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/AddRestaurantCategory", ReplyAction="http://tempuri.org/IRestaurantService/AddRestaurantCategoryResponse")]
        bool AddRestaurantCategory(Enterprise.Logic.Entities.RestaurantCategory restaurantCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurantCategory", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantCategoryResponse")]
        bool UpdateRestaurantCategory(Enterprise.Logic.Entities.RestaurantCategory restaurantCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurantCategory", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantCategoryResponse")]
        bool DeleteRestaurantCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/IsRestaurantHaveMenu", ReplyAction="http://tempuri.org/IRestaurantService/IsRestaurantHaveMenuResponse")]
        bool IsRestaurantHaveMenu(int restaurantId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestaurantServiceChannel : Enterprise.AdminUI.RestaurantService.IRestaurantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<Enterprise.AdminUI.RestaurantService.IRestaurantService>, Enterprise.AdminUI.RestaurantService.IRestaurantService {
        
        public RestaurantServiceClient() {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Enterprise.Logic.Entities.Restaurant GetRestaurant(int id) {
            return base.Channel.GetRestaurant(id);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.Restaurant> GetRestaurants() {
            return base.Channel.GetRestaurants();
        }
        
        public Enterprise.Logic.Entities.Restaurant AddRestaurant(Enterprise.Logic.Entities.Restaurant restaurant) {
            return base.Channel.AddRestaurant(restaurant);
        }
        
        public bool UpdateRestaurant(Enterprise.Logic.Entities.Restaurant restaurant) {
            return base.Channel.UpdateRestaurant(restaurant);
        }
        
        public bool DeleteRestaurant(int id) {
            return base.Channel.DeleteRestaurant(id);
        }
        
        public Enterprise.Logic.Entities.RestaurantCategory GetRestaurantCategory(int id) {
            return base.Channel.GetRestaurantCategory(id);
        }
        
        public System.Collections.Generic.List<Enterprise.Logic.Entities.RestaurantCategory> GetRestaurantCategories() {
            return base.Channel.GetRestaurantCategories();
        }
        
        public bool AddRestaurantCategory(Enterprise.Logic.Entities.RestaurantCategory restaurantCategory) {
            return base.Channel.AddRestaurantCategory(restaurantCategory);
        }
        
        public bool UpdateRestaurantCategory(Enterprise.Logic.Entities.RestaurantCategory restaurantCategory) {
            return base.Channel.UpdateRestaurantCategory(restaurantCategory);
        }
        
        public bool DeleteRestaurantCategory(int id) {
            return base.Channel.DeleteRestaurantCategory(id);
        }
        
        public bool IsRestaurantHaveMenu(int restaurantId) {
            return base.Channel.IsRestaurantHaveMenu(restaurantId);
        }
    }
}
