//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class C__RefactorLog: Entity
    {
    	[DataMember]
        public System.Guid OperationKey { get; set; }
    }
}
