//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Cart: Entity
    {
        
    	[DataMember]
        public string CartId { get; set; }
    	[DataMember]
        public Nullable<int> MenuItemId { get; set; }
    	[DataMember]
        public Nullable<decimal> UnitPrice { get; set; }
    	[DataMember]
        public Nullable<int> Count { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> DateCreated { get; set; }
    	[DataMember]
        public string ImageLocation { get; set; }
    	[DataMember]
        public string Name { get; set; }
    }
}
