//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Order: Entity
    {
        
    	[DataMember]
        public System.DateTime SubmittedDate { get; set; }
    	[DataMember]
        public string CustomerID { get; set; }
    	[DataMember]
        public Nullable<decimal> Total { get; set; }
    	[DataMember]
        public string ContactTelephone { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string State { get; set; }
    	[DataMember]
        public string StreetAddress { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public string FulllName { get; set; }
    	[DataMember]
        public Nullable<int> OrderStatusId { get; set; }
    }
}
