//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class OrderDetail: Entity
    {
        
    	[DataMember]
        public int OrderId { get; set; }
    	[DataMember]
        public int MenuItemId { get; set; }
    	[DataMember]
        public Nullable<int> DeliveryId { get; set; }
    	[DataMember]
        public int Quantity { get; set; }
    	[DataMember]
        public decimal UnitCost { get; set; }
    	[DataMember]
        public string Status { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StatusUpdatedTime { get; set; }
    	[DataMember]
        public Nullable<System.Guid> WorkflowId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ETA { get; set; }
    	[DataMember]
        public string Description { get; set; }
    }
}
