//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class OrderPayment: Entity
    {
        
    	[DataMember]
        public int OrderId { get; set; }
    	[DataMember]
        public string CreditCardNumber { get; set; }
    	[DataMember]
        public string NameOnCard { get; set; }
    	[DataMember]
        public string Address { get; set; }
    	[DataMember]
        public string Country { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string State { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    	[DataMember]
        public string CreditCardType { get; set; }
    }
}
