//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace Enterprise.Logic.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Restaurant: Entity
    {
        
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public int RestaurantCategoryId { get; set; }
    	[DataMember]
        public string LogoImageLocation { get; set; }
    	[DataMember]
        public string SmallLogoImageLocation { get; set; }
    	[DataMember]
        public string BannerImageLocation { get; set; }
    	[DataMember]
        public string MainImageLocation { get; set; }
    	[DataMember]
        public string BackgroundLocation { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string StreetAddress { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string State { get; set; }
    }
}
