//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.AdminUI.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IFileService")]
    public interface IFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DoWork", ReplyAction="http://tempuri.org/IFileService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DoWork", ReplyAction="http://tempuri.org/IFileService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadFile", ReplyAction="http://tempuri.org/IFileService/UploadFileResponse")]
        string UploadFile(Enterprise.Logic.Entities.ImageData imageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadFile", ReplyAction="http://tempuri.org/IFileService/UploadFileResponse")]
        System.Threading.Tasks.Task<string> UploadFileAsync(Enterprise.Logic.Entities.ImageData imageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadImage", ReplyAction="http://tempuri.org/IFileService/UploadImageResponse")]
        void UploadImage(Enterprise.Logic.Entities.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadImage", ReplyAction="http://tempuri.org/IFileService/UploadImageResponse")]
        System.Threading.Tasks.Task UploadImageAsync(Enterprise.Logic.Entities.RemoteFileInfo request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : Enterprise.AdminUI.FileService.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<Enterprise.AdminUI.FileService.IFileService>, Enterprise.AdminUI.FileService.IFileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string UploadFile(Enterprise.Logic.Entities.ImageData imageData) {
            return base.Channel.UploadFile(imageData);
        }
        
        public System.Threading.Tasks.Task<string> UploadFileAsync(Enterprise.Logic.Entities.ImageData imageData) {
            return base.Channel.UploadFileAsync(imageData);
        }
        
        public void UploadImage(Enterprise.Logic.Entities.RemoteFileInfo request) {
            base.Channel.UploadImage(request);
        }
        
        public System.Threading.Tasks.Task UploadImageAsync(Enterprise.Logic.Entities.RemoteFileInfo request) {
            return base.Channel.UploadImageAsync(request);
        }
    }
}
